# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'FunFacts' do
	pod 'Alamofire', '~> 3.1'
	pod ‘SwiftyJSON’, :git => ’https://github.com/SwiftyJSON/SwiftyJSON.git’
end

